Enviando UC09
viniciussousaazevedo/reportverse-backend pull request #28
Opened 2022-07-20 20:29 UTC by bielmenezesc

Implementei o filtro de palavras impróprias, ela está no arquivo BadWordsFilter dentro da pasta Utils.
Dentro do arquivo tem documentado como usar o filtro.

2022-07-21 13:54 UTC, viniciussousaazevedo requested changes

2022-07-21 13:54 UTC, viniciussousaazevedo commented on src/main/java/com/es/reportverse/utils/BadWordsFilter.java
> +    private final static String BAD_WORD_FOUNDED = "O texto inserido foi bloqueado porque uma plavra imprópria foi encontrado nele.";
corrigir "plavra" e "encontrado" (correto seria "encontrada")

2022-07-21 13:54 UTC, viniciussousaazevedo commented on src/main/java/com/es/reportverse/utils/BadWordsFilter.java
> +                    if(content.length == 0) {
acredito que esse if pode ser retirado sem prejudicar na lógica da funcionalidade

2022-07-21 13:54 UTC, viniciussousaazevedo commented on src/main/java/com/es/reportverse/utils/BadWordsFilter.java
> +                    String[] ignore_in_combination_with_words = new String[]{};
utilizar padrão camelCase nesta variável

2022-07-21 13:54 UTC, viniciussousaazevedo commented on src/main/java/com/es/reportverse/utils/BadWordsFilter.java
> +// COMO USAR O FILTRO DE PALAVRÕES:
Favor incluir lógica de filtragem palavras impróprias na criação de publicações

2022-07-21 14:40 UTC, bielmenezesc commented on src/main/java/com/es/reportverse/utils/BadWordsFilter.java
> +    private final static String BAD_WORD_FOUNDED = "O texto inserido foi bloqueado porque uma plavra imprópria foi encontrado nele.";
feito

2022-07-21 14:41 UTC, bielmenezesc commented on src/main/java/com/es/reportverse/utils/BadWordsFilter.java
> +                    String[] ignore_in_combination_with_words = new String[]{};
feito

2022-07-22 18:25 UTC, bielmenezesc commented on src/main/java/com/es/reportverse/utils/BadWordsFilter.java
> +                    if(content.length == 0) {
feito

2022-07-22 18:30 UTC, bielmenezesc commented on src/main/java/com/es/reportverse/utils/BadWordsFilter.java
> +// COMO USAR O FILTRO DE PALAVRÕES:
feito

2022-07-22 18:33 UTC, merged